#!/bin/bash
sudo iptables -F
sudo iptables -X
sudo iptables -Z
sudo iptables -t nat -F
sudo iptables -t nat -X
sudo iptables -t nat -Z
sudo killall redsocks
PGID=$(ps x -o  "%p %r %y %x %c " | grep "ssh\.con" | sed 's/^ *//g' | cut -d ' ' -f 3)
sudo kill -TERM -$PGID
echo "Stopped :)"
