#!/bin/bash
sudo iptables -F
sudo iptables -X
sudo iptables -Z
sudo iptables -t nat -F
sudo iptables -t nat -X
sudo iptables -t nat -Z
sudo killall redsocks
ps x | grep "ssh -CfqND" | head -n 1 | sed 's/^ *//g' | cut -d ' ' -f 1 | xargs sudo kill -9
echo "Stopped :)"
